### ISSUE TITLE
The problem of the image size

### ISSUE THREAD

**Issue by aaronchen98** [hkchengrex/PyTorch-ARCNN#1]
Hello, I wonder if your code only can deal with 400x300 size image? 
If my image size is 180x180, i need to resize my image to 400*300 first, otherwise, 
`RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 300 and 180 in dimension 2 at ../aten/src/TH/generic/THTensor.cpp:711
`

Thank you!

**Comment by hkchengrex** [comment]
Hi, you would need to set the batch size to 1 by appending `--batch_size 1` to `run.py`.
The dataloader cannot collate images with different sizes.

The batch size can be >1 when all the testing images are of the same size.

**Comment by aaronchen98** [comment]
I get it! 
Thank you for your reply.
