### ISSUE TITLE
The SSIM,PSNR-B in Python is not the same with it in  ARCNN with Matlab

### ISSUE THREAD

**Issue by JuZiSYJ** [hkchengrex/PyTorch-ARCNN#2]

**Comment by JuZiSYJ** [comment]
SSIM:
`def calculate_ssim(img1, img2):
    '''calculate SSIM
    the same outputs as MATLAB's
    img1, img2: [0, 255]
    '''

    def ssim(img1, img2):
        C1 = (0.01 * 255) ** 2
        C2 = (0.03 * 255) ** 2

        img1 = img1.astype(np.float64)
        img2 = img2.astype(np.float64)
        kernel = cv2.getGaussianKernel(11, 1.5)
        window = np.outer(kernel, kernel.transpose())

        mu1 = cv2.filter2D(img1, -1, window)[5:-5, 5:-5]  # valid
        mu2 = cv2.filter2D(img2, -1, window)[5:-5, 5:-5]
        mu1_sq = mu1 ** 2
        mu2_sq = mu2 ** 2
        mu1_mu2 = mu1 * mu2
        sigma1_sq = cv2.filter2D(img1 ** 2, -1, window)[5:-5, 5:-5] - mu1_sq
        sigma2_sq = cv2.filter2D(img2 ** 2, -1, window)[5:-5, 5:-5] - mu2_sq
        sigma12 = cv2.filter2D(img1 * img2, -1, window)[5:-5, 5:-5] - mu1_mu2

        ssim_map = ((2 * mu1_mu2 + C1) * (2 * sigma12 + C2)) / (
                (mu1_sq + mu2_sq + C1) *
                (sigma1_sq + sigma2_sq + C2))
        return ssim_map.mean()

    if not img1.shape == img2.shape:
        raise ValueError('Input images must have the same dimensions.')
    if img1.ndim == 2:
        return ssim(img1, img2)
    elif img1.ndim == 3:
        if img1.shape[2] == 3:
            ssims = []
            for i in range(3):
                ssims.append(ssim(img1, img2))
            return np.array(ssims).mean()
        elif img1.shape[2] == 1:
            return ssim(np.squeeze(img1), np.squeeze(img2))
    else:
        raise ValueError('Wrong input image dimensions.')`

**Comment by JuZiSYJ** [comment]
PSNR-B:

`def cAL_psnrb(img_gnd, img):
    '''

    :param img_gnd:  H W 1, 0-255, ori
    :param img:  H W 1  output
    :return:

    have some problem:
    ARCNN  classic5  10 Average PSNR 29.00 SSIM 0.793  PSNRB 28.96---
    ARCNN  LIVE1  10 Average PSNR 28.92 SSIM 0.808  PSNRB 28.87---

    '''

    def cal_bef(img):
        assert img.shape[2] == 1
        B = 8
        h, w = img.shape[:2]
        # print(h,w)
        H = [i for i in range(0, w - 1)]
        H_b = [i for i in range(B - 1, w - 1, B)]
        # print(set(H))
        H_bc = list(set(H).union(set(H_b)) - set(H).intersection(set(H_b)))

        V = [i for i in range(0, h - 1)]
        V_b = [i for i in range(B - 1, h - 1, B)]
        V_bc = list(set(V).union(set(V_b)) - set(V).intersection(set(V_b)))

        D_b = 0
        D_bc = 0

        for i in H_b:
            diff = img[:, i, :] - img[:, i + 1, :]
            D_b += np.sum(diff ** 2)
        for i in H_bc:
            diff = img[:, i, :] - img[:, i + 1, :]
            D_bc += np.sum(diff ** 2)

        for j in V_b:
            diff = img[j, :, :] - img[j + 1, :, :]
            D_b += np.sum(diff ** 2)
        for j in V_bc:
            diff = img[j, :, :] - img[j + 1, :, :]
            D_bc += np.sum(diff ** 2)

        N_hb = h * (w // B - 1)
        N_hbc = h * (w -1) - N_hb
        N_vb = w * (h // B - 1)
        N_vbc = w * (h - 1) - N_vb

        D_b /= (N_hb + N_vb)
        D_bc /= (N_hbc + N_vbc)

        if D_b > D_bc:
            T = np.log2(B) / np.log2(min(h, w))
        else:
            T = 0
        return T * (D_b - D_bc)

    mse = ((img_gnd.astype(np.float) - img.astype(np.float)) ** 2).mean()
    bef = cal_bef(img)
    mse_b = mse + bef

    return 10 * np.log10(1 ** 2 / mse_b)`

**Comment by hkchengrex** [comment]
Are the differences small? They should be very close in terms of L1 distance and I cannot think of a reason for large differences in SSIM/PSNR-B. Minor differences are expected.

**Comment by JuZiSYJ** [comment]
1) The SSIM code is extract from  **BasicSR** or  KAIR，I got the same result in ARCNN paper，However，when i run the **.m** code in ARCNN with 5 other test pic, it is not the same....about 0.1-0.2 eroor

2)The  PSNR-B code is translate from the official  **.m** code in ARCNN, I could not get the result in ARCNN papar in Set5 or LEVEL1 ,it is about 0.x biger than paper, I could not find the BUG :)

**Comment by hkchengrex** [comment]
Well I am not related to the authors of ARCNN in any way, so I cannot speak for their Matlab code. I just made this conversion tool from Matlab to Python. Perhaps you can email the actual authors for that.

**Comment by JuZiSYJ** [comment]
Thanks!
